### ISSUE TITLE
Appear blank when using view

### ISSUE THREAD

**Issue by feelinc** [tyohan/WordPress-MVC-Framework#1]
It was the first time i'm try using the framework and finding below issue.

When i'm using below function at index.php, the screen appear blank.

WpMvc::app()->view->render('post', array(
  'title' => 'TEST',
  'content' => 'CONTENT'
));

the problem appear from TView.php on line 72, it seem you having a endless recursive function there "$this->getActiveThemeDirectory()".

Thank you.

**Comment by tyohan** [comment]
Thanks for report Sule, I made some typo but already fixed. I haven't test it but please confirm me if it's work.

Thanks

**Comment by feelinc** [comment]
Great tyohan, the view are loaded like a charm ^_^.

Thanks.
