### ISSUE TITLE
Fatal error: require_once()

### ISSUE THREAD

**Issue by bepitulaz** [tyohan/WordPress-MVC-Framework#2]
I activated the MVC framework theme, then I found this error message "Fatal error: require_once() [function.require]: Failed opening required '/Users/asepbp/Documents/web-project/mobile-switcher/wp-content/themes/mvc-framework/mvc/WpMvc.php' (include_path='.:/Applications/MAMP/bin/php5.2/lib/php') in /Users/asepbp/Documents/web-project/mobile-switcher/wp-content/themes/mvc-framework/functions.php on line 7"

Where is the WpMvc.php file?

**Comment by bepitulaz** [comment]
oh, there are some updates. solved.

**Comment by tyohan** [comment]
yup, please repull the source. The directory changed from mvc to framework. Thanks
